controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_test_test:
    path: /test/test
    controller: App\Controller\TestController::index
