# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  uploads_dir: '%kernel.project_dir%/public/uploads'
  suit_pictures_dir: '%uploads_dir%/suits'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\File\FileUploader:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'
            $targetDirectory: '%uploads_dir%'
            $fileName: '@App\Service\File\FileNameSlugger'

    App\Service\File\SuitFileUploader:
      arguments:
        $kernelProjectDir: '%kernel.project_dir%'
        $targetDirectory: '%suit_pictures_dir%'
        $fileName: '@App\Service\File\FileNameHash'

    App\Service\Environment\Environment:
        arguments:
            $envName: '%kernel.environment%'

    App\Service\Auth\AuthenticatorFactory:
      arguments:
        $container: '@service_container'

    App\Service\Auth\SSOAuthenticatorInterface:
      factory: '@App\Service\Auth\AuthenticatorFactory'
